/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package untitled;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String getString() {
        return "안 헬로우 월드!";
    }
}
